# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

project 'HHAutoBusiness/HHAutoBusiness.xcodeproj'

target 'HHAutoBusiness' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HHAutoBusiness

  target 'HHAutoBusinessTests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Masonry', '~> 1.0.1'
  pod 'MJRefresh', '~> 3.0.1'
  pod 'MJExtension', '~> 3.0.3'
  pod 'SDCycleScrollView', '~> 1.3'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
  pod 'NullSafe', '~> 1.2.1'
  pod 'SDWebImage', '~> 3.8.1'

end
